### PR TITLE
added dpm cascade models

### PR DESCRIPTION
**Pull request by Jiaolong**
@bmagyar
This PR contains the converted model and malab code for PR
https://github.com/Itseez/opencv_contrib/pull/286

### CODE REVIEW

**Comment by mshabunin** [comment]
Can `testdata/cv/latentsvmdetector` folder be safely deleted in this request?

**Comment by Jiaolong** [comment]
@mshabunin Yes, I have removed `latentsvmdetector` folder.

**Comment by Jiaolong** [comment]
Please consider to merge this branch! Thanks!

**Comment by Jiaolong** [comment]
Thanks! :+1:

**Pull request merged**
