### PR TITLE
GSoC 2015 - Structured Light module test data

### PR DESCRIPTION
**Pull request by RobertaRavanelli**
Pull request for adding data to test GrayCodePattern class - reconstruction of plane object (GSoC 2015 - Structured Light module).

### CODE REVIEW

**Comment by alalek** [comment]
1) For what contrib PR is this patch?
2) Please squash commits into one, there are a lot of intermediate changes.

**Comment by RobertaRavanelli** [comment]
It is for [GSoC 2015 Structured Light module final term PR](https://github.com/Itseez/opencv_contrib/pull/340).

**Comment by alalek** [comment]
1) Branch names for pull request in opencv_contrib and opencv_extra should have the same name (this is requirement of our infrastructure to merge opencv_extra patches).
2) This patch is very big: it is about 64Mb. I'm not sure that you need PNG quality for images here. Are tests/sample work you with JPG images?
This command will reduce size of images to ~6Mb:
```
for i in *.png; do echo $i; convert -quality 70 "$i" "${i%.*}.jpg"; done
```
You may play with quality settings (to pass your tests). Do not forget to change PNG->JPG in tests.

**Comment by RobertaRavanelli** [comment]
I made a new pull request from a branch with the same name of opencv_contrib repository:
[link to new PR](https://github.com/Itseez/opencv_extra/pull/268).

**Pull request closed without merging**
