### PR TITLE
added latentsvm cascade testing data

### PR DESCRIPTION
**Pull request by Jiaolong**
I have pointed this issue in
https://github.com/Itseez/opencv_contrib/issues/191

### CODE REVIEW

**Comment by vpisarev** [comment]
@Jiaolong, our merge tool works in a strange way; to get this PR merged, can you make a dummy PR to the main opencv (master branch) from a branch with the same name "test_data_lsvm_cascade"?

**Comment by Jiaolong** [comment]
@vpisarev I have created a [branch](https://github.com/Jiaolong/opencv/tree/test_data_lsvm_cascade) with the same name but I couldn't send a dummy PR without changing anything in the main opencv. Could you tell me how to make it? Thanks!

**Comment by mshabunin** [comment]
@Jiaolong, can you please also remove existing `models_VOC2007` folder? As for PR to main repository, I think you can make some dummy change, for example remove first space on [this line](https://github.com/Itseez/opencv/blob/d9148ea6041578f12d942d7d36b3eb251e8c2828/modules/ml/include/opencv2/ml.hpp#L69).

**Comment by alalek** [comment]
I believe it is better to make a dummy empty commit:
```
git commit --allow-empty -m "commit for opencv_extra PR 248"
```

**Comment by Jiaolong** [comment]
Thanks for reviewing this PR! I would like to close this PR as soon as the new [DPM module](https://github.com/Itseez/opencv_contrib/pull/286) and the corresponding testing data #264 are merged, because this PR is only for the previous version of DPM module., i.e. the latent svm cascade module.

**Pull request closed without merging**
