### PR TITLE
GSOC 2015: sfm module test data

### PR DESCRIPTION
**Pull request by edgarriba**

### CODE REVIEW

**Comment by alalek** [comment]
Please remove unnecessary intermediate changes like removed files (squash commits into one: `git rebase -i upstream/master`)

**Comment by edgarriba** [comment]
@alalek not sure if I messed up ...

**Comment by alalek** [comment]
I have no idea how you get this =)
Merge commits in patch is evil.

```
git remote add upstream https://github.com/Itseez/opencv_extra.git
git fetch upstream
git checkout sfm
git rebase -i upstream/master
# "pick" first commit and "f" for others, save+exit
git push -f origin sfm
```

**Comment by edgarriba** [comment]
before I put s instead of f

**Pull request merged**
